version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_DB: lawgic
      POSTGRES_USER: lawgic
      POSTGRES_PASSWORD: lawgic
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lawgic -d lawgic"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nestjs-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://lawgic:lawgic@postgres:5432/lawgic?schema=public
      JWT_SECRET: segredo_super_secreto
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./api/.env:/app/.env:ro # Opcional: montar .env se necessário

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
