services:
  postgres:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_DB: lawgic
      POSTGRES_USER: lawgic
      POSTGRES_PASSWORD: lawgic
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lawgic -d lawgic"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
