export const AUTH_REPOSITORY = 'AUTH_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const NOTIFICATIONS_REPOSITORY = 'NOTIFICATIONS_REPOSITORY';
export const FORMS_REPOSITORY = 'FORMS_REPOSITORY';
